CC = gcc
FLAGS = -Wall -Wextra -Werror
NAME = ft_cat
SRC = srcs/*.c
HEADER = includes

all: $(NAME)

$(NAME):
	$(CC) $(SRC) $(FLAGS) -I $(HEADER) -o $(NAME)

clean:
	/bin/rm -f $(NAME)

fclean: clean

re: fclean al
